# PR Labeler Configuration

# Mobile App
mobile:
  - changed-files:
      - any-glob-to-any-file: "apps/mobile/**/*"

# Auth Service
auth-service:
  - changed-files:
      - any-glob-to-any-file: "services/auth-service/**/*"

# Shared Packages
packages:
  - changed-files:
      - any-glob-to-any-file: "packages/**/*"

# UI Design System
ui:
  - changed-files:
      - any-glob-to-any-file: "packages/ui-design-system/**/*"

# API Contracts
api:
  - changed-files:
      - any-glob-to-any-file: "packages/api-contracts/**/*"

# Feature Flags
feature-flags:
  - changed-files:
      - any-glob-to-any-file: "packages/feature-flags/**/*"

# Infrastructure
infra:
  - changed-files:
      - any-glob-to-any-file: "infra/**/*"

# CI/CD
ci:
  - changed-files:
      - any-glob-to-any-file: ".github/**/*"

# Documentation
docs:
  - changed-files:
      - any-glob-to-any-file:
          - "docs/**/*"
          - "**/*.md"

# Database
database:
  - changed-files:
      - any-glob-to-any-file:
          - "**/prisma/**/*"
          - "**/migrations/**/*"

# Dependencies
dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - "**/package.json"
          - "**/package-lock.json"
          - "**/pnpm-lock.yaml"
